ci: pin molecule to version 2.22
Some change introduced in the newly released v3.0 causes my build to
fail.

ERROR: Failed to pre-validate.
{'lint': ['must be of string type']}

Failing build:
https://travis-ci.com/eliasnorrby/dotfiles/builds/150432699

Releases:
https://github.com/ansible-community/molecule/releases